marketplace/base/urls.py
from django.urls import path
from django.contrib.auth import views  as auth_views

from  . import views
from .forms import LoginForm


app_name = 'base'


urlpatterns =[

    path('', views.index , name='index'),
    path('signup/', views.signup, name='signup'),
    path('contact/', views.contact, name='contact'),
    path('login/', auth_views.LoginView.as_view(template_name='base/login.html', authentication_form=LoginForm), name='login')
]

marketplace/conversation/urls.py
from django.urls import path

from . import views

app_name = 'conversation'

urlpatterns = [
    path('',views.inbox,name='inbox'),
    path('<int:pk>/',views.detail,  name='detail'),
    path('new/<int:product_pk>/', views.new_conversation, name='new'),
]

marketplace/marketplace/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


from marketplace import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('inbox/',include('conversation.urls')),
    path('products/', include('product.urls')),
    path('dashboard/', include('dashboard.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

marketplace/product/urls.py
from django.urls import path

from . import views

app_name = 'product'

urlpatterns = [
    path('', views.browse, name='browse'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/', views.new_product, name='new'),
    path('<int:pk>/edit/', views.edit_product, name='edit'),
    path('<int:pk>/delete/', views.delete_product, name='delete'),
]

marketplace/product/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=255)
    '''Displaying Categories'''

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

    '''Adding products'''


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=20)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField()
    image = models.ImageField(upload_to='product_images', blank=True, null=True)
    is_sold = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name='products', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name

marketplace/product/forms.py
from django import forms
from .models import Product



INPUT_CLASSES = 'w-full py-4 px-6 rounded-xl border'
class NewProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('category', 'name', 'description', 'price', 'image',)

        widgets = {
            'category': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'price': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            }),
        }

class EditProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('name', 'description', 'price', 'image','is_sold')

        widgets = {
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'price': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            }),
        }

marketplace/product/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect

from product.forms import NewProductForm, EditProductForm
from product.models import Product, Category


def browse(request):
    query = request.GET.get('query', '')
    products = Product.objects.filter(is_sold=False)
    category_id = request.GET.get('category', 0)
    categories = Category.objects.all()

    if category_id:
        products = products.filter(category_id=category_id)
    if query:
        products = products.filter(name__icontains=query)
    return render(request, 'product/browse.html',
                  {'products': products,
                   'query': query,
                   'categories': categories,
                   'category_id': int(category_id),
                   })


# Create your views here.
def detail(request, pk):
    product = get_object_or_404(Product, pk=pk)
    related_products = Product.objects.filter(category=product.category, is_sold=False).exclude(pk=pk)[0:3]
    return render(request, 'product/detail.html',
                  {'product': product,
                   'related_products': related_products,
                   })


@login_required
def new_product(request):
    if request.method == 'POST':
        form = NewProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save(commit=False)
            product.created_by = request.user
            product.save()
            return redirect('product:detail', pk=product.id)
    else:
        form = NewProductForm()
    return render(request, 'product/product.html',
                  {
                      'form': form,
                      'title': 'New product',
                  })


@login_required
def delete_product(request, pk):
    product = get_object_or_404(Product, pk=pk, created_by=request.user)
    product.delete()

    return redirect('dashboard:index')


@login_required
def edit_product(request, pk):
    product = get_object_or_404(Product, pk=pk, created_by=request.user)
    if request.method == 'POST':
        form = EditProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            product.save()
            return redirect('product:detail', pk=product.id)
    else:
        form = EditProductForm(instance=product)
    return render(request, 'product/product.html',
                  {
                      'form': form,
                      'title': 'Edit product',
                  })

marketplace/product/templates/product/browse.html
{% extends 'base/base.html' %}
{% block title %}
Browse
{% endblock %}

{% block body %}
    <div class="pb-6 grid grid-cols-4 gap-4 bg-gray-100">
        <div class="col-span-1">
            <form method="get" action="{% url 'product:browse' %}">
                <input name="query" class="w-full py-4 px-6 border rounded-xl"
                       type="text" value="{{ query }}" placeholder="Find a product..">
                <button class="mt-2 py-4 px-8 text-lg bg-green-500 text-white rounded-xl">
                    Search
                </button>
            </form>
            <hr class="my-6">
            <p class="font-semibold">Categories</p>
            <ul>
                {% for category in categories %}
                    <li class="py-2 px-2 rounded-xl{% if category.id == category_id %} bg-gray-500 {% endif %}">
                        <a href="{% url 'product:browse'%}?query={{query}}&category={{category.id}}">{{category.name}}</a>
                    </li>
                {% endfor %}
            </ul>
            <hr class="my-6">
            <p class="font-semibold"></p>
            <ul>
                <li class="py-4 px-8 rounded-xl bg-green-350">
                    <a href="{% url 'product:browse' %}">Clear </a>
                </li>
            </ul>


        </div>
        <div class ="col-span-3">
            <div class="grid grid-cols-3 gap-3">
            {% for product in products %}
            <div>
                <a href="{% url 'product:detail'  product.id %}">
                <div>
               <img src="{{ product.image.url }}" class="rounded-t-xl" style="width: 400px;  height:600px;" >
                </div>
                <div class="p-6 bg-white rounded-b-xl text-2xl">
                 {{product.name}}
                    </div>
                    <p class="text-gray-500">Price {{product.price}}</p>
                    </a>
            </div>
        {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

marketplace/product/templates/product/detail.html
{% extends 'base/base.html' %}

{% block title %}Products |
{{product.name}}
{% endblock %}
{% block body %}
<div class="grid grid-cols-5 gap-6">
    <div class="col-span-3">
        <img src="{{ product.image.url }}" class="rounded-xl" style="width:400px; height:400px;">
    </div>
    <div class="col-span-2 p-6 bg-gray-199 rounded-xl">
        <h1 class="mb-6 text-3xl">{{product.name}}</h1>
        <p class="text-gray-500"><strong>Price:</strong>{{product.price}}</p>
        <p class="text-gray-500"><strong>Seller:</strong>{{product.created_by.username}}</p>
        {% if product.description %}
        <p class="text-gray-700">
            <strong class="text-gray-500">Description:
            </strong><br>
            {{product.description}}
        </p>
        {% endif %}
        {% if request.user == product.created_by %}
        <div class="mt-6 p-6 bg-white rounded-xl">

            <p> It's your product</p>
                        <a href="{% url 'product:edit' product.id %}" class="inline-block mt-6 px-6 py-6 text-lg font-semibold bg-blue-500 text-white rounded-xl hover:bg-blue-700">Edit</a>
            <a href="{% url 'product:delete' product.id %}" class="inline-block mt-6 px-6 py-6 text-lg font-semibold bg-red-500 text-white rounded-xl hover:bg-red-700">Delete</a>

        </div>

        {% else %}

        <a href="{% url 'conversation:new' product.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-green-500 text-red rounded-xl hover:bg-green-700">
            Contact Seller
        </a>
        {% endif %}
    </div>
</div>
    <div class="mt-20 px-6 py-3 bg-gray-100 rounded-xl">
        <h2 class="py-6 mb-12 text-2xl text-center ">More Items</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for product in related_products %}
            <div class="flex">
                <a href="{% url 'product:detail'  product.id %}">
                <div>
               <img src="{{ product.image.url }}" class="rounded-t-xl" style="width:400px; height:400px;" >
                </div>
                <div class="p-6 bg-white rounded-b-xl text-2xl">
                 {{product.name}}
                    </div>
                    <p class="text-gray-500 p-3 text-xl">Price {{product.price}}</p>
                    </a>
            </div>
        {% endfor %}
    </div>
    </div>

{% endblock %}

marketplace/product/templates/product/product.html
{% extends 'base/base.html' %}


{% block title%} {{ title }}

{% endblock %}

{% block body %}
    <h1 class="mb-6 text-3xl">{{title}}</h1>
    <form method="post" action="." enctype="multipart/form_data">
        {% csrf_token %}
        <div class="space-y-4">
            {{form.as_p}}
        </div>


        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                {{field.errors}}
                {% endfor %}
                {{form.non_field_errors}}
            </div>
        {% endif %}
    <button class="py-4 px-8 text-lg bg-grey-500 hover:bg-grey-700 rounded-xl text-white">
            Submit
        </button>
    </form>

{% endblock %}