marketplace/base/urls.py
from django.urls import path
from django.contrib.auth import views  as auth_views

from  . import views
from .forms import LoginForm


app_name = 'base'


urlpatterns =[

    path('', views.index , name='index'),
    path('signup/', views.signup, name='signup'),
    path('contact/', views.contact, name='contact'),
    path('login/', auth_views.LoginView.as_view(template_name='base/login.html', authentication_form=LoginForm), name='login')
]

marketplace/conversation/urls.py
from django.urls import path

from . import views

app_name = 'conversation'

urlpatterns = [
    path('',views.inbox,name='inbox'),
    path('<int:pk>/',views.detail,  name='detail'),
    path('new/<int:product_pk>/', views.new_conversation, name='new'),
]

marketplace/dashboard/urls.py
from django.urls import path

from . import views

app_name= 'dashboard'

urlpatterns=[
    path('',views.index, name='index')
]

marketplace/marketplace/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


from marketplace import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('inbox/',include('conversation.urls')),
    path('products/', include('product.urls')),
    path('dashboard/', include('dashboard.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

marketplace/product/urls.py
from django.urls import path

from . import views

app_name = 'product'

urlpatterns = [
    path('', views.browse, name='browse'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/', views.new_product, name='new'),
    path('<int:pk>/edit/', views.edit_product, name='edit'),
    path('<int:pk>/delete/', views.delete_product, name='delete'),
]

marketplace/base/models.py
from django.db import models

# Create your models here

marketplace/base/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth.models import User


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4',
    }
    ))

    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your email',
        'class': 'w-full py-4',
    }
    ))

    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4',
    }
    ))

    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Repeat password',
        'class': 'w-full py-4',
    }
    ))


class LoginForm(AuthenticationForm):

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4',
    }
    ))

    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4',
    }
    ))

marketplace/base/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect

from base.forms import SignupForm
from product.models import Category, Product


# Create your views here.
def index(request):
    categories = Category.objects.all()
    products = Product.objects.filter(is_sold=False)[0:6]
    return render(request, 'base/index.html',
                  {
                      'products': products,
                      'categories': categories
                  }
                  )


def contact(request):
    return render(request, 'base/contact.html')


def signup(request):
    if request.method=='POST':
        form= SignupForm(request.POST)

    if form.is_valid():
        form.save()
        return redirect('/login')

    form = SignupForm()
    return render(request, 'base/signup.html',
                  {'form': form
                   })

marketplace/base/templates/base/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width", initial-scale="1.0">
    <script src="https://tailwindcss.com"></script>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <title>
        {% block title %}
        Base page
        {% endblock %}
    </title>
</head>
<body>
<nav class ="py-6 px-6 flex justify-between items-center border-b border-gray-200">
    <a href="/" class="text-xl font-semibold">Market</a>
    <div class="space-x-6">
        <a href="{% url 'product:new' %}" class="text-lg font-semibold hover:text-gray-500">New Item</a>
        <a href="{% url 'product:browse'%}" class="text-lg font-semibold hover:text-gray-500">Browse</a>
        {% if request.user.is_authenticated %}
                        <a href="{% url 'conversation:inbox' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">
            Inbox
        </a>
                        <a href="{% url 'dashboard:index' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">
            Dashboard
        </a>
                <a href="#" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">
            Log Out
        </a>
        {% else %}
        <a href="{% url 'base:signup' %}" class="px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl hover:bg-red-700">Sign up
        </a>
        <a href="{% url 'base:login' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">
            Log in
        </a>
        {% endif %}
    </div>

</nav>
<div class="px-6 py-6">
{% block body %}

{% endblock %}
</div>
<footer class="py-6 px-6 flex justify-between bg-gray-800">
<div class="w-2/3 pr-10">
    <h3 class="mb-5 font-semibold text-gray-400">About</h3>
    <p class="text-lg text-gray-500">market for everybody</p>
</div>
    <div class="w-1/3">
        <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>
        <ul class="space-y-2">
        <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">About</a></li>
        <li><a href="{% url 'base:contact' %}" class="text-lg text-teal-500 hover:text-teal-700">Contact</a></li>
                <li>
            <a href="#" class="text-lg text-teal-500 hover:text-teal-700">
            Privacy
            </a>
        </li>
                <li>
            <a href="#" class="text-lg text-teal-500 hover:text-teal-700">
            Terms of use
            </a>
        </li>
            </ul>
    </div>
    </footer>
</body>
</html>

marketplace/base/templates/base/contact.html
{% extends 'base/base.html' %}
{% block title %}Contact{% endblock %}
{% block body %}
    <h1>The Contact page</h1>
{% endblock %}

marketplace/base/templates/base/index.html
{% extends 'base/base.html' %}
{% block body %}


    <h1>The Front page</h1>
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center ">Newest Items</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for product in products %}
            <div>
                <a href="{% url 'product:detail'  product.id %}">
                <div>
               <img src="{{ product.image.url }}" class="rounded-t-xl" style="width: 400px;  height:600px;" >
                </div>
                <div class="p-6 bg-white rounded-b-xl text-2xl">
                 {{product.name}}
                    </div>
                    <p class="text-gray-500">Price {{product.price}}</p>
                    </a>
            </div>
        {% endfor %}
    </div>
    </div>
        <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center ">Categories</h2>

        <div class="grid grid-cols-3 gap-3 flex">
            {% for  category in categories %}
            <div>
                <a href="#">
                <div class="p-6 bg-red rounded-b-xl">
                 <h2 class="text-2xl">{{ category.name }}</h2>
                <p class="text-gray-500"> {{ category.products.count }} items</p>
                </div>
                </a>
            </div>
            {% endfor %}
        </div>
        </div>
{% endblock %}

marketplace/base/templates/base/login.html
{% extends 'base/base.html'%}
{% block title %}Login{% endblock %}
{% block body %}
<div class="w-1/2 my-6 p-6 mx-auto bg-gray-100 ruonded-xl">
    <h1 class="mb-6 text-3xl">Log in</h1>
    <form method="post" >
    {% csrf_token %}
        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{form.username}}
        </div>
        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{form.password}}

        </div>
        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                {{field.errors}}
                {% endfor %}
                {{form.non_field_errors}}
            </div>
        {% endif %}
        <button class="py-4 px-8 text-lg bg-grey-500 hover:bg-grey-700 rounded-xl text-white">
            Submit
        </button>
    </form>
</div>
{% endblock %}

marketplace/base/templates/base/signup.html
{% extends 'base/base.html'%}
{% block title %}Sign up{% endblock %}
{% block body %}
<div class="w-1/2 my-6 p-6 mx-auto bg-gray-100 ruonded-xl">
    <h1 class="mb-6 text-3xl">Sign up</h1>
    <form method="post" >
    {% csrf_token %}
    {{form.non_field_errors}}
        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{form.username}}
        </div>
        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{form.password1}}
        </div>
        <div class="mb-3">
            <label class="inline-block mb-2">Repeat password</label><br>
            {{form.password2}}
        </div>
        <div class="mb-3">
            <label class="inline-block mb-2">Email</label><br>
            {{form.email}}
        </div>
        <button class="py-4 px-8 text-lg bg-grey-500 hover:bg-grey-700 rounded-xl text-white">
            Submit
        </button>
    </form>
</div>
{% endblock %}